### ISSUE TITLE
Temporary  file is read only on windows

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#427] opened 2019-10-29 02:16 UTC
https://travis-ci.org/astropy/pytest-doctestplus/jobs/604227968#L221

./ci-helpers/travis/setup_dependencies_common.sh: line 93: /dev/fd/62: Read-only file system

It refers to this line: ``$revised_command > >(tee $_tmp_output_file) 2>&1`` from below

```
            python ci-helpers/travis/hack_version_numbers.py $_tmp_spec_conflicts "$@" > $_tmp_updated_conda_command
            revised_command=$(cat $_tmp_updated_conda_command)
            echo $revised_command
            # Try it; if it still has conflicts then just give up
            $revised_command > >(tee $_tmp_output_file) 2>&1
            _exitval="$?"
            if [[ -n $(grep "conflicts with explicit specs" $_tmp_output_file) ]]; then
                echo "STOPPING conda attempts because unable to resolve conda pinning issues"
                rm -f $_tmp_output_file
                return 1
            fi
        fi
```

cc @mwcraig @djhoese

**Comment by bsipocz** [comment] 2019-10-29 03:04
(Bare in mind this is on the windows job only, linux works as expected)

**Comment by djhoese** [comment] 2019-10-29 13:22
Oh Windows.

That's very strange. I would assume it is talking about the `_tmp_output_file` being read only? Iirc this temporary file is in the current directory, maybe we (ci-helpers) doesn't have write access to the current directory? We could make a more official (`mktemp`?) temporary file that we should have more explicit write access to.

Other thought is if we are writing to the same temporary filename multiple times and maybe Windows hasn't closed it yet and is complaining about two processes writing to the same file.

**Comment by mwcraig** [comment] 2019-10-29 13:56
The problem isn't that the specific file is read only, it is that the pipe created to feed `tee`, etc. is read only. The error is:

```
./ci-helpers/travis/setup_dependencies_common.sh: line 409: /dev/fd/62: Read-only file system
```
It was "fixed" in #405 by removing the `tee` and keeping fingers crossed that the job wouldn't go too long without output (that was the issue that led to using `tee` in the first place).

I guess I missed another spot where `tee` occurs though. I'm going to have to resist the temptation to try to do a proper fix until the weekend, unfortunately.

**Comment by bsipocz** [comment] 2019-10-29 17:46
Originally I thought that this may be a root cause of the issues I was running into yesterday, but it wasn't, so there is no reason to rush with any fix for this one.

**Comment by djhoese** [comment] 2019-10-31 14:35
>  it is that the pipe created to feed tee

Ok, but why is this happening? Why is it read only? I added the tee stuff because I was running in to the commands running too long and travis was timing out. Granted, that shouldn't happen in an up to date environment creation.

**Comment by djhoese** [comment] 2019-11-17 19:46
I'm running in to this now with one of my projects. I think it is leading to a 10 minute time out on travis on the Windows environment.

**Closed** 2019-11-18 21:31 UTC
Labels: bug, travis
